# Schema for the configuration files of the Workflow module.
workflow.settings:
  type: config_object
  label: 'Workflow settings'
  mapping:
    workflow_states_per_page:
      type: integer
      label: 'Number of workflow states per page'

workflow.workflow.*:
  type: config_entity
  label: 'Workflow settings'
  mapping:
    id:
      type: string
      label: 'ID'
    status:
      type: boolean
      label: 'Status'
    label:
      type: label
      label: 'Label'
    module:
      type: string
      label: 'Module'
    options:
      type: mapping
      label: 'Options'
      mapping:
        name_as_title:
          type: integer
          label: 'Use the workflow name as the title of the workflow transition form'
        fieldset:
          type: integer
          label: 'Show the form in a fieldset'
        options:
          type: string
          label: 'How to show the available states'
        schedule_enable:
          type: boolean
          label: 'Enable scheduling in workflow transition form'
        schedule_timezone:
          type: integer
          label: 'Show a timezone when scheduling a transition'
        always_update_entity:
          type: integer
          label: 'Always update the entity last updated timestamp'
        comment_log_node:
          type: integer
          label: 'Show comment on the Content edit form'
        watchdog_log:
          type: integer
          label: 'Log messages upon state change'

field.storage_settings.workflow:
  type: mapping
  label: 'Workflow settings'
  mapping:
    workflow_type:
      type: string
      label: 'Workflow'
    allowed_values:
      type: sequence
      label: 'Allowed values list'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_function:
      type: string
      label: 'Allowed values function'

field.field_settings.workflow:
  type: mapping
  label: 'Workflow settings'

action.configuration.workflow_node_next_state_action:
  type: mapping
  label: 'Configuration for the Change entity to next Workflow state action'
  mapping:
    field_name:
      type: string
      label: 'The field name of the entity'
    to_sid:
      type: string
      label: 'The the new state ID'
    comment:
      type: string
      label: 'The comment to add to the transition'
    force:
      type: boolean
      label: 'Indicator if the transition must be forced, even if not allowed'

action.configuration.workflow_node_given_state_action:
  type: mapping
  label: 'Configuration for the Change entity to new Workflow state action'
  mapping:
    field_name:
      type: string
      label: 'The field name of the entity'
    to_sid:
      type: string
      label: 'The the new state ID'
    comment:
      type: string
      label: 'The comment to add to the transition'
    force:
      type: boolean
      label: 'Indicator if the transition must be forced, even if not allowed'
